2024-10-21 04:43:47.817 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 04:43:47.822 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 04:43:47.930 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 04:43:48.072 | ERROR    | app.modules.heatmap.services:query_heatmap:85 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 80, in query_heatmap
    meta = HeatmapModel.find_heatmap_infos({
  File "/workspace/refactor/vss_controller/app/modules/heatmap/models.py", line 38, in find_heatmap_infos
    return FaceModel.find(
NameError: name 'FaceModel' is not defined

2024-10-21 04:52:17.125 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 04:52:17.129 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 04:52:17.138 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 04:52:17.190 | ERROR    | app.modules.heatmap.services:query_heatmap:85 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 83, in query_heatmap
    }).sort("timestamp", pymongo.ASCENDING)
AttributeError: 'dict' object has no attribute 'sort'

2024-10-21 06:30:32.696 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 06:30:32.700 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 06:30:32.707 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 06:30:32.744 | ERROR    | app.modules.heatmap.services:query_heatmap:85 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 80, in query_heatmap
    meta = HeatmapModel.find_heatmap_infos({
  File "/workspace/refactor/vss_controller/app/modules/heatmap/models.py", line 42, in find_heatmap_infos
    ).sort("timestamp", pymongo.ASCENDING)
AttributeError: 'dict' object has no attribute 'sort'

2024-10-21 06:32:08.434 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 06:32:08.439 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 06:32:08.448 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 06:32:08.520 | ERROR    | app.modules.heatmap.services:query_heatmap:85 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 80, in query_heatmap
    meta = HeatmapModel.find_heatmap_infos({
  File "/workspace/refactor/vss_controller/app/modules/heatmap/models.py", line 42, in find_heatmap_infos
    ).sort("timestamp", pymongo.ASCENDING)
AttributeError: 'dict' object has no attribute 'sort'

2024-10-21 06:45:05.845 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 06:45:05.849 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 06:45:05.862 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 06:45:05.936 | ERROR    | app.modules.heatmap.services:query_heatmap:85 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 80, in query_heatmap
    meta = HeatmapModel.find_heatmap_infos({
  File "/workspace/refactor/vss_controller/app/modules/heatmap/models.py", line 42, in find_heatmap_infos
    {"timestamp": pymongo.ASCENDING}
NameError: name 'pymongo' is not defined

2024-10-21 06:46:46.881 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 06:46:46.891 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 06:46:46.900 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 06:46:46.964 | ERROR    | app.modules.heatmap.services:query_heatmap:165 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 98, in query_heatmap
    background_object = urlparse(meta[-1]["image_path"], allow_fragments=False)
TypeError: string indices must be integers

2024-10-21 06:59:12.634 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 06:59:12.634 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 06:59:12.642 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 06:59:12.684 | ERROR    | app.modules.heatmap.services:query_heatmap:165 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 98, in query_heatmap
    background_object = urlparse(meta[-1]["image_path"], allow_fragments=False)
TypeError: string indices must be integers

2024-10-21 07:04:44.336 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 07:04:44.336 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 07:04:44.386 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 07:04:44.436 | ERROR    | app.modules.heatmap.services:query_heatmap:165 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 98, in query_heatmap
    background_object = urlparse(meta[-1]["image_path"], allow_fragments=False)
TypeError: string indices must be integers

2024-10-21 07:07:35.569 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 07:07:35.569 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 07:07:35.577 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 07:07:35.635 | ERROR    | app.modules.heatmap.services:query_heatmap:166 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 99, in query_heatmap
    background_object = urlparse(meta[-1]["image_path"], allow_fragments=False)
TypeError: string indices must be integers

2024-10-21 07:09:49.394 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 07:09:49.404 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 07:09:49.417 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 07:09:49.671 | ERROR    | app.modules.heatmap.services:query_heatmap:166 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 99, in query_heatmap
    background_object = urlparse(meta[-1]["image_path"], allow_fragments=False)
TypeError: string indices must be integers

2024-10-21 07:16:07.417 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 07:16:07.417 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 07:16:07.425 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 07:18:20.748 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 07:18:20.749 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 07:18:20.757 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 07:18:20.789 | ERROR    | app.modules.heatmap.services:query_heatmap:163 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 96, in query_heatmap
    background_object = urlparse(meta["result"][-1]["image_path"], allow_fragments=False)
IndexError: list index out of range

2024-10-21 07:55:24.936 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 07:55:24.943 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 07:55:25.036 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 08:37:46.875 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 08:37:46.875 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 08:37:46.896 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
2024-10-21 08:37:47.142 | ERROR    | app.modules.heatmap.services:query_heatmap:163 - Traceback (most recent call last):
  File "/workspace/refactor/vss_controller/app/modules/heatmap/services.py", line 92, in query_heatmap
    if len(meta["result"]) == 0:
KeyError: 'result'

2024-10-21 08:40:36.751 | INFO     | app.modules.heatmap.routers:heatmap_query:37 - Client IP: 172.23.0.1
2024-10-21 08:40:36.752 | INFO     | app.modules.heatmap.routers:heatmap_query:38 - User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-10-21 08:40:36.765 | INFO     | app.modules.heatmap.services:query_heatmap:77 - device_id: 1111, time_from: 17294859000, time_to: 17294859064
